### ISSUE TITLE
Icons not visible in new Jetbrains UI

### ISSUE THREAD

**Issue by SpoonOfDoom** [leinardi/mypy-pycharm#107]
### Step 1: Are you in the right place?
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of the plugin.

### Step 2: Describe your environment
 - Plugin version: `0.14`
 - PyCharm/IDEA version: `PyCharm 2023.1 (Professional Edition) (Build #PY-231.8109.197)`
 - Mypy version: `1.2.0`

#### Steps to reproduce:

  1. Enable new UI in PyCharm
  2. Install Plugin

#### Observed Results:

  * None of the icons are visible, making the plugin practically unusable.
![grafik](https://user-images.githubusercontent.com/649040/233334350-a342bc0c-f090-4fe3-a32b-65e16b956d6f.png)

  

#### Expected Results:

  * A way to interact with the plugin without hovering over all areas where some icons *could* be.

#### Relevant Code:

not relevant

**Comment by leinardi** [comment]
Hi @SpoonOfDoom, thank you for the report. I should have fixed this issue, could you please give it a try?

[mypy-plugin-0.15.0.zip](https://github.com/leinardi/mypy-pycharm/files/11304919/mypy-plugin-0.15.0.zip)

If you confirm that it's fixed I'll release a new version.

**Comment by SpoonOfDoom** [comment]
@leinardi Seems to work now:
![grafik](https://user-images.githubusercontent.com/649040/233955572-e1929e4c-19dc-4bf5-8295-696fd9256e2e.png)

Thanks for the fix!

**Comment by leinardi** [comment]
Thank you for confirming that the fix works.
