### ISSUE TITLE
Offer to install mypy if not yet installed.

### ISSUE THREAD

**Issue by dmwyatt** [leinardi/mypy-pycharm#2]
Instead of a bunch of unexpected exception errors in the event log it would be better to handle mypy not yet being installed a smoother fashion.

**Comment by Salaander** [comment]
I came here to create this issue. I am glad somebody already did it and you are working on it.
Good job on the plugin! :)

**Comment by leinardi** [comment]
Hi @dmwyatt, @Salaander 
I have made some change to show the user something better than a scary stacktrace if mypy is missing:
![image](https://user-images.githubusercontent.com/273338/44999235-f50fd200-afbb-11e8-89ad-3ce0a305537d.png)

![image](https://user-images.githubusercontent.com/273338/44999240-00fb9400-afbc-11e8-942b-ecd5af70d8a9.png)

I have a test build here, I would appreciate if you can test it and give me feedback: 
[mypy-plugin-0.8.0.zip](https://github.com/leinardi/mypy-pycharm/files/2346398/mypy-plugin-0.8.0.zip)

**Comment by Salaander** [comment]
I installed and tested the test build. Works the same way as It shows on your screenshot. Fine for me. Thanks.
