### ISSUE TITLE
Auto detect mypy bin in virtual env

### ISSUE THREAD

**Issue by iddan** [leinardi/mypy-pycharm#25]
**Is your feature request related to a problem? Please describe.**
After installing the plugin I was surprised to see an exception raised because of `mypy` not found in the project even though it is available in the virtual env.

**Describe the solution you'd like**
I'd like the auto detect to look for the mypy bin in the virtual env.

**Additional context**
It's best practice to install mypy as a dev dependency inside a virtual env

**Comment by tkellogg** [comment]
I just installed `mypy-pycharm` and it autodetected `mypy` in a virtual env. Has this been resolved?

**Comment by leinardi** [comment]
Oh yeah, probably this issue was fixed when I implemented the autodetection. Closing now.
