### ISSUE TITLE
Disable realtime scanning but keep widget? (Major peformance issues in windows)

### ISSUE THREAD

**Issue by x9sim9** [leinardi/mypy-pycharm#40]
I am having severe performance issues with the background scanning of my py in pycharm causing the ide to become unresponsive. Is there a way to keep the widget but disable all background scanning using mypy.

thanks,
Simon

**Comment by leinardi** [comment]
Hi @x9sim9, you can follow these instructions to disable the real time inspection: https://github.com/leinardi/mypy-pycharm#inspection-severity

**Comment by x9sim9** [comment]
Hi Leinardi,

unfortunately setting the inspection severity to
No highlighting, only fix
does not stop the mypy realtime scanning

I need other inspections to still run on the code, so I cannot exclude the directories from scanning.

As soon as I rename the mypy.exe to an invalid location all my performance issues resolve but now I cannot use the widget

How do i completely disable realtime scanning, as pycharm is incredibly slow when its running

thanks,
Simon
