### ISSUE TITLE
Support for .pyi files

### ISSUE THREAD

**Issue by bdelanghe** [leinardi/mypy-pycharm#51]
### Step 1: Are you in the right place?
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of the plugin.

### Step 2: Describe your environment
 - Plugin version: `0.10.6`
 - PyCharm/IDEA version: `2019.2.4`
 - Mypy version: ` 0.740`

#### Steps to reproduce:

  1. create new package
  2. add foo.py _with no annotations_
  3. add foo.py _with annotations_

#### Observed Results:

  * When running mypy from terminal with -p flag all of the package passes
  * When running from mypy-pycharm missing annotation errors are thrown.  
  

#### Expected Results:

* Stub files should be used when running the type check.

_I'm fairly new to mypy and to the plugin. This might just be something that I'm doing inccorectly_

**Comment by fgblomqvist** [comment]
You can see how the command that this plugin is constructed here:
https://github.com/leinardi/mypy-pycharm/blob/b37d3b2fcdb5b819f383a5a77ebdfbe18f6f686c/src/main/java/com/leinardi/pycharm/mypy/mpapi/MypyRunner.java#L269-L301

Generally, it will run this:
`mypy --show-column-numbers --follow-imports silent <files separated by spaces>` (and might also include a config flag). If you run this command in your situation, does mypy pick up the pyi? If not, try passing the pyi file as well. Curious about the results. Shouldn't be hard to solve this one.

**Comment by LecrisUT** [comment]
What exactly was the resolution here?

I am encountering this issue because:
- If `file.py` and `file.pyi` is passed it gives error of `Duplicate module name`
- When I navigate the non-stub file, it is full of error because if you pass only that file it has no typing
- When running without any input (all files) mypy is happy because the stub files are used
