### ISSUE TITLE
Mypy tool window button icons missing in 2022.1 EAP

### ISSUE THREAD

**Issue by theY4Kman** [leinardi/mypy-pycharm#88]
- Plugin version: `com.leinardi.pycharm.mypy (0.12.1)`
 - PyCharm/IDEA version: `PY-221.3427.103`

![image](https://user-images.githubusercontent.com/33840/154552542-d96a609d-0064-489e-a979-06448e2153e6.png)

**Comment by leinardi** [comment]
Hi @theY4Kman, I can't reproduce the issue, I tried with both PyCharm and IDEA:
![image](https://user-images.githubusercontent.com/273338/154801841-7f602ef5-cc47-4bbc-a5e4-3a9e90eed2ea.png)

Can you try with the latest build of 2022.1 EAP?

**Comment by intgr** [comment]
I've seen missing icon issues in other places as well with EAP releases -- I think it's just regressions in EAP, nothing to do with this plugin.

**Comment by theY4Kman** [comment]
Oh, yes, my apologies; they pushed a new version right after opening this, and the issue disappeared.
